### ISSUE TITLE
Suggestion: export ApiBodyDocument

### ISSUE THREAD

**Issue by postatum** [advanced-rest-client/api-body-document#12]
Hi.
This issue is the same as https://github.com/advanced-rest-client/api-documentation/issues/21

**Comment by jarrodek** [comment]
NPM is down and I can't publish a package I need for it to work so I'll do this after npm is up again.

**Comment by postatum** [comment]
> NPM is down and I can't publish a package I need for it to work so I'll do this after npm is up again.

Thanks a lot! :partying_face:
